version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: build1
      buildspec: build1.yml
    
    - identifier: build2
      buildspec: build2.yml

    - identifier: build3
      buildspec: build3.yml
      depend-on:
        - build1
        - build2